name: Build Helper

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: src
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: autoav-ftc-linux
            artifact_extension:
            asset_name: autoav-ftc-linux
            cmd: build-linux
          - os: windows-latest
            artifact_name: autoav-ftc-windows
            artifact_extension: .exe
            asset_name: autoav-ftc-windows-amd64.exe
            cmd: build-win
          - os: macos-latest
            artifact_name: autoav-ftc-mac
            artifact_extension:
            asset_name: autoav-ftc-macos-amd64
            cmd: build-mac

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install, Compile, and Build Binary
      run: |
        npm ci
        npm run build
        npm run ${{ matrix.cmd }}
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}_v${{ env.RELEASE_VERSION}}${{ matrix.artifact_extension }}
        tag: ${{ github.ref }}
